name: Build and Push

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    container:
      image: ghcr.io/elastic-ee/ci-image:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run script
        run: |
          echo $REGISTRY_PASSWORD | docker login $REGISTRY -u $REGISTRY_USER --password-stdin
          bash ./build.sh
